name: uhandisi
description: An Elite:\ Dangerous companion tool that aids in engineering.
version: 0.0.1
publish_to: "none"
# homepage: https://www.example.com

environment:
  sdk: ">=2.16.1 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7
  lints: ^2.0.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  intl: ^0.18.0
  google_fonts: ^3.0.1
  flutter_redux: ^0.10.0

flutter:
  uses-material-design: true
